# Contenido de la página principal
index:
  # Sección header/hero
  header:
    title: "SATBAA"
    subtitle: "Sistema de Alerta Temprana Basada en Agentes Autónomos"
    image: "Inicio_SitioWeb.png"

  # Sección introducción
  introduction:
    title: "Introducción"
    image: "/src/img/fire.png"
    paragraphs:
      - "A lo largo de la historia de la humanidad han ocurrido diversos fenómenos, ya sean de carácter natural como las inundaciones, sismos, erupciones volcánicas, entre otros, así como conflictos causados por la misma sociedad. Estos fenómenos traen consigo consecuencias tales como los daños a las infraestructuras y los bienes a la población, al igual que víctimas fatales."
      - "Afortunadamente, los diversos avances tecnológicos han permitido acercarnos a la identificación de causas y circunstancias asociadas a su origen y a la frecuencia con la que ocurren, como ejemplo tenemos a los Sistemas de Seguridad y Alerta Temprana de Riesgos (SSATR)."
      - "Este proyecto se orienta al desarrollo de un sistema de detección y alerta oportuna de desastres naturales y antrópicos, que provea ayuda en la toma de decisiones a dos tipos de usuarios: **a) víctimas y b) equipos de respuesta y gestión de desastres…**"
    buttonText: "Saber más"

  # Objetivo general
  objective:
    title: "Objetivo General"
    content: "Desarrollar un SSATR basado en un Sistema Multi‑Agente compuesto por agentes heterogéneos (cognitivos y reactivos), objetos y artefactos, que identifique riesgos y amenazas personales y colectivas con base en un modelo computacional de interacción que comprenda personas y otros sistemas informáticos, que actúe en beneficio de los usuarios y salvaguarde la integridad de los datos de estos."

  # Beneficios
  benefits:
    title: "Beneficios"
    items:
      - icon: "feed"
        description: "Proporcionar información pertinente a los usuarios para mejorar las condiciones de las víctimas de un evento desastroso que los lleve a evitar el peligro y minimizar el riesgo."
      - icon: "diversity_2"
        description: "Aumentar la eficiencia y coordinación de los equipos de emergencia durante sus intervenciones."
      - icon: "group_add"
        description: "Apoyar a los tomadores de decisiones para mejorar las condiciones de seguridad y gestión del riesgo."
    buttonText: "Ver objetivos específicos"
    buttonRoute: "/ProyectoInvestigacion"

  # Aplicaciones desarrolladas
  applications:
    title: "Aplicaciones desarrolladas"
    staticApps:
      - label: "API de Eventos Naturales"
        image: "/src/img/APIEN-Light-Icon.png"
        description: "Integra información de datos de monitoreo ambiental oficiales (en esta fase considera...)"
        route: "/PagApiEnv"
      - label: "Semáforo de la Roya del Café"
        image: "/src/img/SCC-Light-Icon.png"
        description: "Estima la probabilidad de la presencia de roya en las matas de café a partir de datos..."
        route: "/PagSrc"
      - label: "Semáforo de Riesgo Personal"
        image: "/src/img/SRP-Light-Icon.png"
        description: "Permite calcular el índice de riesgo (IR) que presenta una persona ante un desastre natural a través..."
        route: "/PagSrp"

  # Artículos y publicaciones
  articles:
    title: "Artículos y publicaciones"
    items:
      - image: "/src/img/grietas.png"
        title: "Hacia un semáforo de riesgo personal para sismos en la República Mexicana"
        authors: "Rodrigo Vázquez Espino, Wulfrano Arturo Luna‑Ramírez, Anasol Peña‑Rios, Miguel Capllonch Juan."
        summary: "Resumen del artículo publicado. Puedes personalizar este texto."
        route: "/PagArticulo1"
      - image: "/src/img/2.png"
        title: "Hacia un semáforo de riesgo personal para sismos en la República Mexicana"
        authors: "Rodrigo Vázquez Espino, Wulfrano Arturo Luna‑Ramírez, Anasol Peña‑Rios, Miguel Capllonch Juan."
        summary: "Segundo resumen de ejemplo. Personaliza aquí."
        route: "/PagArticulo2"
    moreArticlesText: "Ver más publicaciones"
    moreArticlesRoute: "/PagArticulos"

  # Disciplinas y tecnologías
  disciplines:
    title: "Disciplinas y tecnologías"
    image: "/src/img/celular.png"
    paragraphs:
      - "Aunque este proyecto podría englobarse dentro de la disciplina de Ciencias de la Computación, vale la pena señalar que por la naturaleza del problema es de carácter interdisciplinario."
      - "Por estar fuertemente relacionado su proceso con la indagación, desarrollo y evaluación con el Diseño Centrado en el Usuario, tiene fuerte presencia del Diseño de Interfaces e Interacción y la Ergonomía Cognitiva, ya que se relaciona con usuarios reales, la Usabilidad, la Inteligencia Artificial, las Tecnologías Inmersivas, las interacciones Humano‑Computadora y el Cómputo Ubicuo."

  # Equipo de colaboradores
  team:
    title: "Equipo de colaboradores"
    buttonText: "Ver todo el equipo colaborador"
    buttonRoute: "/Colaboradores"
